### ISSUE TITLE
[ERROR]Error: Message: Process unexpectedly closed with status 1

### ISSUE THREAD

**Issue by UserHen** [Flangvik/Bobber#2]
Hi, I was wondering if you have come across this error before? All requirements installed. Roadtx works fine individually. 

Many thanks

[INFO] SSH is not enabled. Monitoring local database file /root/.evilginx/data.db
[SUCCESS] Found session with captured cookie for : 
[INFO] Using RoadTools to retrieve JWT tokens for 
[ERROR]Error: Message: Process unexpectedly closed with status 1

**Comment by HenryEgress** [comment]
This was due to running it as root. Do not get error when run as user

**Comment by panicacid** [comment]
I'm having the same issue:

"[INFO] SSH is not enabled. Monitoring local database file /root/.evilginx/data.db
[SUCCESS] Found session with captured cookie for : XXXXX@XXXXXXX.onmicrosoft.com
[INFO] Using RoadTools to retrieve JWT tokens for XXXXX@XXXXXXX.onmicrosoft.com
[ERROR]Error: Message: Process unexpectedly closed with status 1"

I presume it's because I'm running this on a headless VPS and it's not liking the fact that it can't launch a browser, I've got firefox installed though but yeah. If you're trying to run this in a headless VPS I'm guessing (and it is just a guess) that's where the issue is.

Will try building this setup on a VM with a display and see how I get on and report back.

**Comment by Root-Kunal** [comment]
Hey, so I had this same issue and managed to fix it allowing me to run Bobber headless on a VPS.

The first issue I had was that the VPS I was using downloaded an incorrect version of Firefox (if you're using Ubuntu it might've done the same and installed an old version of Firefox via Snap). I removed the Firefox version and then installed the most up to date version using this guide: https://support.mozilla.org/en-US/kb/install-firefox-linux.

I then had to use the environment variable `MOZ_HEADLESS=1` (so `export MOZ_HEADLESS=1`) and Bobber worked fine in headless mode. You may only need to do this part :)

Hope this helps!

**Comment by Flangvik** [comment]
Great stuff @Root-Kunal, thanks for the great input!
